sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install tox-travis "tox>=2.7,<3dev" codecov
script: tox
after_success:
  - codecov
